config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'users/new'

  get 'sessions/new'

  root 'welcome#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :request, :will, :search, :users
  post "will/import", to: "will#import"
  get '/instructions', to: "welcome#instructions"
  get '/faq', to: "welcome#faq"
  get '/release', to: "welcome#release"
  get '/contact', to: "welcome#contact"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  validates :applicant, presence: true
  validates :testator_first, presence: true
  validates :testator_last, presence: true
  validates :status, presence: true
  validates :lsuc, presence: true
end

app/models/testator.rb
class Testator < ApplicationRecord
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :dob, presence: true
  # validates :city_of_birth, presence: true
  # validates :country_of_birth, presence: true
  belongs_to :firm
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
end

app/models/will.rb
class Will < ApplicationRecord
  validates_presence_of :first_name, :last_name, :lawyer_name, :firm_name, :lsuc, :telephone, :year

  def self.search(search)
    where("first_name ILIKE :search \
          or last_name ILIKE :search \
          or alt_last_name ILIKE :search \
          or city_of_birth ILIKE :search \
          or province_of_birth ILIKE :search \
          or country_of_birth ILIKE :search \
          or last_resided ILIKE :search", {search: "%#{search}%"})
  end

  def self.import(file)
    CSV.foreach(file.path, encoding:'iso-8859-1:utf-8', headers: true) do |row|
      next if row.to_s.start_with?(",,,")
      Will.create! row.to_hash.merge({"approved" => false})
    end
  end
end

app/controllers/application_controller.rb
require "csv"

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    status = params[:status] || "All"
    if status == "All"
      @requests = Request.all
    else
      @requests = Request.where(status: status)
    end
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"requests.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def new
    @request = Request.new
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update_attributes(request_params)
      render 'show'
    else
      render 'edit'
    end
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      render 'confirmation'
    else
      flash[:danger] = "Please enter all required fields."
      render 'new'
    end

  end

  def confirmation
  end

  def destroy
    Request.find(params[:id]).destroy
    flash[:success] = "Request deleted"
    render 'index'
  end

  def show
    @request = Request.find(params[:id])
  end


  private
  def request_params
    params.require(:request).permit(:applicant, :testator_first, :testator_last, :testator_dob, :testator_city, :email, :telephone, :testator_alt, :testator_province, :testator_country, :testator_last_resident, :status, :lsuc)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :logged_in_user

  def index
  end

  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  # def new
  #   @user = User.new
  # end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false
  layout 'welcome'

  def index
  end

end

app/controllers/will_controller.rb
class WillController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    approved = params['approved']
    if approved == 'true'
      @wills = Will.where(approved: true)
    elsif approved == 'false'
      @wills = Will.where(approved: false)
    else
      @wills = Will.all
    end
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"wills.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def new
    @will = Will.new
  end

  def edit
    @will = Will.find(params[:id])
  end

  def update
    @will = Will.find(params[:id])
    if @will.update_attributes(will_params)
      render 'show'
    else
      render 'edit'
    end
  end

  def create
    if params[:id] == "search-form"
      if params[:search]
        @wills = Will.search(params[:search]).order('created_at DESC')
      else
        @wills = Will.all.order('created_at DESC')
      end
      render 'index'
    else
      @will = Will.new(will_params)
      if @will.save
        @thank_you = "Thank you for registering with us. You registered the following will:"
        render 'confirmation'
      else
        flash.now[:danger] = "Please enter all required fields."
        render 'new'
      end
    end
  end

  def confirmation
  end

  def show
    @will = Will.find(params[:id])
  end

  def import
    Will.import(params[:file])
    flash[:success] = "Wills successfully imported."
    render 'new'
  end

  def destroy
    Will.find(params[:id]).destroy
    flash[:success] = "Will deleted"
    render 'index'
  end

  private
  def will_params
    params.require(:will).permit(:first_name, :last_name, :alt_last_name, :dob, :city_of_birth, :province_of_birth, :country_of_birth, :last_resided, :lawyer_name, :firm_name, :lsuc, :telephone, :year, :approved)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/find/new.html.erb
    <h1>CCLA Wills</h1>
    <p>Welcome to the County of Carleton Law Association Wills database. To request a will location, please enter testator information below.</p>

    <em>* denotes a required field</em>
    <%= form_for :request do |f| %>
      <table class="table">
        <tr><td>*Your name:</td><td><%= f.text_field :applicant %></td></tr>
        <tr><td>Your email:</td><td><%= f.text_field :email %></td></tr>
        <tr><td>Telephone:</td><td><%= f.text_field :telephone %></tr>
        <tr><td>*Testator's first name:</td><td><%= f.text_field :testator_first %></td></tr>
        <tr><td>*Testator's last name:</td><td><%= f.text_field :testator_last %></td></tr>
        <tr><td>Testator's alternate name:</td><td><%= f.text_field :testator_alt %></td></tr>
        <tr><td>*Date of birth:</td><td><%= f.date_field :testator_dob %></td></tr>
        <tr><td>*City of birth:</td><td><%= f.text_field :testator_city %></td></tr>
        <tr><td>Province of birth:</td><td><%= f.text_field :testator_province %></td></tr>
        <tr><td>Last resident in (city)</td><td><%= f.text_field :testator_last_resident %></td></tr>
      </table>
      <%= f.submit "Submit Request" %>
    <% end %>
    <br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wills</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="sidebar" class="col-xs-2">
          <%= link_to image_tag("WCLogo-trans.png", class: "wc-logo"), controller: :welcome,  action: :index %>
          <div class="menu">
            <% if logged_in? %>
              <p><strong>Logged in as</strong> <%= current_user.name %></p>
              <div class="nav-item">
                <%= link_to "Profile", current_user, class: "btn btn-default btn-primary" %>
              </div>
              <div class="nav-item">
                <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-default btn-primary" %>
              </div>
              <div class="nav-item">
                <%= link_to "Search (staff only)", {controller: :search, action: :index}, class: "btn btn-default btn-primary" %>
              </div>
            <% end %>
            <div class="nav-item">
              <%= link_to "Find a Will", {controller: :request, action: :new}, class: "btn btn-default btn-primary" %>
            </div>
            <div class="nav-item">
              <%= link_to "Register a Will", {controller: :will, action: :new}, class: "btn btn-default btn-primary" %>
            </div>
          </div>
          <%= image_tag "cclacenprigrayrgb300-small.png", class: "ccla-logo" %>
        </div>
        <div id="content" class="col-xs-10">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>

          <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wills</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    </body>
</html>

app/views/register/new.html.erb
<h1>CCLA Wills</h1>
<div>
<p>To register a new will, please enter the following testator information:</p>

<p>If you haven't already registered your firm with us, please do that now:</p>
<%= link_to "Register Firm", "firm#new" %>
</div>

    <em>* denotes a required field</em>
    <%= form_for :testator, url: register_index_url do |f| %>
      <table class="table">
        <tr><td>*Testator's first name:</td><td><%= f.text_field :first_name %></td></tr>
        <tr><td>*Testator's last name:</td><td><%= f.text_field :last_name %></td></tr>
        <tr><td>Testator's alternate name:</td><td><%= f.text_field :alt_last_name %></td></tr>
        <tr><td>*Date of birth:</td><td><%= f.date_field :dob %></td></tr>
        <tr><td>*City of birth:</td><td><%= f.text_field :city_of_birth %></td></tr>
        <tr><td>Province of birth:</td><td><%= f.text_field :province_of_birth %></td></tr>
        <tr><td>Last resident in (city):</td><td><%= f.text_field :last_resided %></td></tr>
        <tr><td>Firm:</td><td><%= f.collection_select :firm_id, Firm.order(:name),:id,:name,include_blank: true %></td></tr>
      </table>
      <%= f.submit "Register Will" %>
    <% end %>
    <br /><br />

app/views/request/confirmation.html.erb
<strong>Thank you for your request! We will contact you within two business days.</strong>

app/views/request/edit.html.erb
<p>Update request status.</p>

<p><strong>Request applicant: </strong>: <%= @request.applicant %></p>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@request) do |f| %>

      <%= f.label :status %>
      <%= f.select :status, ['New', 'In Progress', 'Closed'], class: 'form-control' %>
      <br />
      <%= f.submit "Update Status", class: "btn btn-default btn-primary" %>
    <% end %>

app/views/request/index.csv.erb
<%- headers = ['Applicant', 'Email', 'Telephone', 'LSUC', 'Testator First Name', 'Testator Last Name', 'Alt Name', 'DOB', 'City', 'Province', 'Last Resided In' ] -%>
<%= CSV.generate_line headers %>
<%- @requests.each do |request| -%>
  <%= CSV.generate_line([request.applicant,
                         request.email,
                         request.telephone,
                         request.lsuc,
                         request.testator_first,
                         request.testator_last,
                         request.testator_alt,
                         request.testator_dob,
                         request.testator_city,
                         request.testator_province,
                         request.testator_last_resident,
                         request.status]) -%>
<%- end -%>

app/views/request/index.html.erb
Display <%= form_tag "/request", method: 'get' do %><%= select_tag 'status', '<option>All</option><option>New</option><option>In Progress</option><option>Closed</option>'.html_safe %> <%= submit_tag 'Go' %><% end %>

<% if @requests %>
<table class="table">
  <tr><th>Applicant</th><th>Email</th><th>Telephone</th><th>LSUC</th><th>Testator</th><th>Testator Alt. Name</th><th>DOB</th><th>City</th><th>Province</th><th>Last Resided In</th><th>Created On</th><th>Status</th></tr>
<% for request in @requests do %>
  <tr>
    <td><%= link_to request.applicant, request %></td>
    <td><%= request.email %></td>
    <td><%= request.telephone %></td>
    <td><%= request.lsuc %></td>
    <td><%= request.testator_first %> <%= request.testator_last %></td>
    <td><%= request.testator_alt %></td>
    <td><%= request.testator_dob %></td>
    <td><%= request.testator_city %></td>
    <td><%= request.testator_province %></td>
    <td><%= request.testator_last_resident %></td>
    <td><%= request.created_at.to_date %></td>
    <td><%= request.status || "New" %></td>
    <td><%= link_to "Delete", request, method: :delete, data: {confirm: "Are You Sure?"} %></td></tr>
<% end %>
</table>

<%= link_to 'Export to CSV', request_index_path(format: :csv), class: "btn btn-default btn-primary" %>

<% else %>

  <p>There are currently no requests in the system.</p>

<% end %>

app/views/request/new.html.erb
<div class= "row">
<div class= "col-xs-6">
    <h1>Will Request Form</h1>
    <p>Welcome to the County of Carleton Law Association Wills database. To request a will location, please enter testator information below. At this time, searches will only be conducted for lawyers licensed by the LSUC, or other provinces’ equivalent.</p>

    <em>* denotes a required field</em>
    <%= form_for :request, url: request_index_url, :html => {:class => "form-inline"} do |f| %>
      <div class="form-label"><strong>Contact Information</strong></div>
  <div class= "form-group">
    <%= f.label :applicant, "*Your name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :applicant, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :email, "*Your email:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :telephone, "Your telephone:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :telephone, class: "form-control" %>
    </div>
  </div>
  <div class= "form-group">
    <%= f.label :lsuc, "*Your LSUC:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :lsuc, class: "form-control" %>
    </div>
  </div>
  <div class="form-label"><strong>Testator Information</strong></div>
  <div class= "form-group">
    <%= f.label :testator_first, "*Testator's first name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_first, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_last, "*Testator's last name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_last, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_alt, "Alternate last name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_alt, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_dob, "Date of birth (YYYY-MM-DD):", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_dob, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_city, "City of birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_city, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_province, "Province of birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_province, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :testator_last_resident, "Last resided in (city):", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :testator_last_resident, class: "form-control" %>
    </div>
  </div>
  <div class= "form-group">
    <div class= "col-md-6">
      <%= f.hidden_field :status, value: "New", class: "form-control" %>
    </div>
  </div>
  <div id="submit">
    <%= f.submit "Submit Request", class: "btn btn-default btn-primary" %>
  </div>
    <% end %>
</div>
</div>

app/views/request/show.html.erb
<p>Thank you for your request. We will contact you within two business days.</p>

<br />
<p>Your request contained the following data:</p>
<table>
  <tr><td><strong>Applicant: </strong></td><td><%= @request.applicant %></td></tr>
  <tr><td><strong>Email: </strong></td><td><%= mail_to @request.email %></td></tr>
  <tr><td><strong>Telephone: </strong></td><td><%= @request.telephone %></td></tr>
  <tr><td><strong>LSUC: </strong></td><td><%= @request.lsuc %></td></tr>
  <tr><td><strong>Testator Name: </strong></td><td><%= @request.testator_first %> <%= @request.testator_last %></td></tr>
  <tr><td><strong>Alternate Name: </strong></td><td><%= @request.testator_alt %></td</tr>
  <tr><td><strong>Date of Birth: </strong></td><td><%= @request.testator_dob %></td></tr>
  <tr><td><strong>City of Birth: </strong></td><td><%= @request.testator_city %></td></tr>
  <tr><td><strong>Province of Birth: </strong></td><td><%= @request.testator_province %></td></tr>
  <tr><td><strong>Country of Birth: </strong></td><td><%= @request.testator_country %></td></tr>
  <tr><td><strong>Last Resided In: </strong></td><td><%= @request.testator_last_resident %></td></tr>
  <tr><td><strong>Request Status: </strong></td><td><%= @request.status %></td</tr>
  <tr><td><strong>Date created: </strong></td><td><%= @request.created_at.to_date %></td</tr>
</table>

<%= button_to 'Change Status', {action: "edit"}, class: "btn btn-default btn-primary", method: :get %>

app/views/search/index.html.erb
<div>
<h1>Staff Interface</h1>
<ul><li><%= link_to "Search for a Will", action: :new %></li>
  <li><%= link_to "Browse Wills", controller: :will, action: :index %></li>
  <li><%= link_to "Browse open requests", controller: :request, action: :index %></li>
</ul>
</div>

app/views/search/new.html.erb
<h1>Find a Will</h1>
<%= form_tag(:controller => "will", :method => "get", id: "search-form", class: "form-inline") do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Wills" %>
    <br /><br />
  </div>
  <div id="submit">
    <%= submit_tag "Search", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p><strong>User</strong></p>
<p><strong><%= @user.name %></strong> (<%= @user.email %>)</p>

app/views/welcome/_logonav.html.erb
<%= image_tag("wclogo-letterbox.png", class: "logo") %>
<% @curr_page = request.env['PATH_INFO'] %>
<div id="link-bar">
  <table>
    <tr>
      <% if @curr_page != "/" %>
        <td><a href="/">HOME</a></td>
      <% end %>
      <td><a href="/instructions">INSTRUCTIONS</a></td><td><a href="/release">RELEASE</a></td><td><a href="/faq">FAQ</a></td><td><a href="/contact">CONTACT</a></td></tr>
  </table>
</div>

app/views/welcome/release.html.erb
<div class="welcome">
  <%= render "logonav" %>
  <div class="content">
    <h2>Release</h2>

    <div id="release-text">
      <p>In order to secure your client’s permission to release information about their will to Will Check, we have prepared a release for you to customize for your office.</p>
      <ul><li><a href='/sample_release.docx'>Will Check Release – English</a></li></ul>
    </div>
  </div>
</div>

app/views/will/confirmation.html.erb
<strong>Thank you! The will has been registered.</strong>

app/views/will/index.html.erb
Display <%= form_tag "/will", method: 'get' do %><%= select_tag 'approved', '<option value="all">All</option><option value="true">Approved</option><option value="false">Not approved</option>'.html_safe %> <%= submit_tag 'Go' %><% end %>
<% if @wills %>
  <br />
  <p>Displaying <%= @wills.count %> wills.
  <%= link_to 'Export to CSV', will_index_path(format: :csv), class: "btn btn-default btn-primary" %> </p>
  <table class="table">
    <tr><th>Name</th><th>Year</th><th>Date Created</th></tr>
    <% for will in @wills do %>
      <tr>
        <td><%= link_to "#{will.first_name} #{will.last_name}", will %></td>
        <td><%= will.year %></td>
        <td><%= will.created_at.to_date %>
        <td><%= will.approved ? "Approved" : "Not approved" %></td>
    </tr>
  <% end %>
  </table>
<% else %>

  <p>Will successfully deleted. Click <%= link_to "here", action: :index %> to see more wills.</p>

<% end %>

app/views/will/new.html.erb
<div class= "row">
<div class= "col-xs-6">
<h1>Will Registration</h1>
<div>
  <p>To register a new will, please enter the following testator information:</p>

</div>

<em>* denotes a required field</em>
<%= form_for :will, url: will_index_url,:html => {:class => "form-inline"} do |f| %>
  <div class="form-label"><strong>Testator Information</strong></div>
  <div class= "form-group">
    <%= f.label :first_name, "*Testator's first name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :last_name, "*Testator's last name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :alt_last_name, "Alternate last name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :alt_last_name, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :dob, "Date of Birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.date_field :dob, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :city_of_birth, "City of Birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :city_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :province_of_birth, "Province of Birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :province_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :country_of_birth, "Country of Birth:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :country_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :last_resided, "Last resided in (city):", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :last_resided, class: "form-control" %>
    </div>
  </div>

  <div class="form-label"><strong>Present Location of Will</strong></div>
  <div class= "form-group">
    <%= f.label :lawyer_name, "*Lawyer name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :lawyer_name, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :firm_name, "*Firm name:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :firm_name, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :lsuc, "*LSUC number:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :lsuc, class: "form-control" %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.label :telephone, "*Telephone number:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :telephone, class: "form-control" %>
    </div>
  </div>
  <div class= "form-group">
    <%= f.label :year, "*Year of will:", class: "col-md-6 control-label" %>
    <div class= "col-md-6">
      <%= f.text_field :year, class: "form-control" %>
    </div>
  </div>
  <div class= "form-group">
    <div class= "col-md-6">
      <%= f.hidden_field :approved, value: false, class: "form-control" %>
    </div>
  </div>
  <div id="submit">
    <%= f.submit "Register Will", class: "btn btn-default btn-primary" %>
  </div>
<% end %>
</div>
<div id="multi-upload" class="col-xs-6">
  <p>To register multiple wills, please download and use this template:</p>
  <p><strong>Please note that dates must be entered in the format YYYY-MM-DD</strong></p>
<a href="/wills-blank.csv">wills-blank.csv</a>
<br /><br />
<p>Upload CSV data</p>
<br />
<%= form_tag({controller: :will, action: :import, class: "form-inline"}, {multipart: true}) do %>
  <div class= "form-group">
    <%= file_field_tag :file, class: "btn btn-default btn-primary" %>
  </div>
  <div id="submit">
    <%= submit_tag "Upload", class: "btn btn-default btn-primary" %>
  </div>
  <p>If you have difficulties uploading, you can also email your .csv file to <a href="mailto:library@ccla-abcc.ca">library@ccla-abcc.ca</a></p>
<% end %>
</div>
</div>

app/views/will/success.html.erb
<%= flash[:notice] %>